### ISSUE TITLE
Cannot import module

### ISSUE THREAD

**Issue by EamonnHarrison** [sh1989/finput-react#1]
Have installed finput-react using npm/yarn (confirmed that the files are in my node_modules folder) but get the error `Module not found: finput-react` when I add the code `import FinputReact from 'finput-react';` to one of my component files.

**Comment by sh1989** [comment]
Thanks @EamonnHarrison, I'll look into this.

**Comment by sh1989** [comment]
Ok, just pulled down https://registry.npmjs.org/finput-react/-/finput-react-1.0.0.tgz and cracked it open. Looks like the distributable form of the code isn't being bundled into the .tgz, which is why it's not being resolved. I've fixed this, will push the build to npm tonight.
